---
- name: gitlab-ctl start
  ansible.builtin.command:
    cmd: gitlab-ctl start

- name: gitlab-ctl stop
  ansible.builtin.command:
    cmd: gitlab-ctl stop

- name: gitlab-ctl restart
  ansible.builtin.command:
    cmd: gitlab-ctl restart

- name: gitlab-ctl reconfigure
  ansible.builtin.command:
    cmd: gitlab-ctl reconfigure

- name: gitlab-rake root password reset
  ansible.builtin.expect:
    command: "gitlab-rake 'gitlab:password:reset[root]'"
    responses:
      .*password.*: "{{ gitlab_root_user_password | string }}"
    timeout: 120
  no_log: true
